CREATE TABLE IF NOT EXISTS rosters (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    roster_name VARCHAR(100) NOT NULL,
    description TEXT,
    unit_ids JSON,
    total_cost INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);